- name: Install Vagrant and Python3.5 from SCL
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - rh-python35
    - sclo-vagrant1

- name: Check Vagrant
  shell: '{{ vagrant_scl_exec }} vagrant --version'
  become: true

- name: Install Packages
  yum: 
    name: '{{ item }}' 
    state: present
  become: true
  with_items:
    - libvirt
    - libvirt-devel
    - kvm
    - seabios
    - git
    - gcc
    - libffi-devel
    - openssl-devel
    - patch
    - libguestfs-tools-c

- name: Run VMs under root
  lineinfile: 
    dest: /etc/libvirt/qemu.conf
    line: 'user = "root"'

- name: Enable libvirtd service
  service:
    name: libvirtd
    state: started 
    enabled: yes

- name: Install Pipsi
  shell: '{{ python3_scl_exec }} pip3.5 install pipsi'
  become: true

- name: Install Pew
  shell: '{{ python3_scl_exec }} pipsi --bin-dir=/usr/bin install pew'
  become: true

- name: Install Pipenv
  shell: '{{ python3_scl_exec }} pipsi --bin-dir=/usr/bin install pipenv'
  become: true

- name: Prepare `pipenv`
  shell: '{{ python3_scl_exec }} pipenv --three'
  args:
    chdir: /root/payload
  become: true

- name: Patch `pipenv` delegator to prevent deadlock
  patch:
    src: ../../../../patches/delegator.patch
    dest: /root/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/vendor/delegator.py
    strip: 0
  become: true

- name: Patch `pipenv` cli to prevent deadlock
  patch:
    src: ../../../../patches/cli.patch
    dest: /root/.local/venvs/pipenv/lib/python3.5/site-packages/pipenv/cli.py
    strip: 0
  become: true

- name: Install `pipenv`
  shell: '{{ python3_scl_exec }} pipenv install --dev --ignore-hashes'
  args:
    chdir: /root/payload
  become: true
