# file: roles/init/tasks/main.yml
---

- name: Update Yum
  yum: name=* state=latest

- name: Install nano, git, etc
  yum: pkg={{ item }} state=installed
  with_items:
     - git
     - nano
     - curl
     - gcc
     - kernel-devel
     - wget
     - vim
     - man
     - unzip
